defaults:
  - default
  - _self_

exp_name: sf_refinenet

data:
  train:
    batch_size: 8
    dataset:
      crop_size: [392, 784]
  val_dataset_names:
    - things

model:
  _target_: dispvit.models.refinenet.RefineNet
  regressor:
    _target_: dispvit.models.dispvit.DispViT
    encoder_type: vitl
  regressor_pretrained_path: logs/sf_rvc_finetune_bs64/ckpts/checkpoint.pt
  extractor:
    _target_: dispvit.models.extractor.ConvNextExtractor
    output_dim: 128
    stochastic_depth_prob: 0.2
    _init_weights: True
  embed_dim: 128
  num_blocks: 5
  window_size: 4
  num_heads: 4
  mlp_ratio: 4
  drop: 0
  attn_drop: 0
  drop_path: 0
  return_intermediate: True

max_epochs: 67

loss:
  _target_: training.loss.RefineLoss
  disp:
    weight: [0.7, 0.7, 0.8, 1.0, 1.0]
  regress:
    disp_weight: 0.1
    logit_weight: 1.0
  loss_type: l1
  gram:
    weight: 1.0

logging:
  log_dir: logs/${exp_name}
  log_freq: 10
  log_level_primary: DEBUG
  log_level_secondary: WARNING
  all_ranks: False
  scalar_keys_to_log:
    train:
      keys_to_log:
        - loss_objective
        - loss_disp
        # - loss_disp_vit
        - loss_disp_regress
    val:
      keys_to_log: []

optim:
  frozen_module_names: ["regressor"]

  amp:
    enabled: False

  options:
    lr:
      - scheduler:
          _target_: fvcore.common.param_scheduler.CompositeParamScheduler
          schedulers:
            - _target_: fvcore.common.param_scheduler.LinearParamScheduler
              start_value: 1e-7
              end_value: 5e-4
            - _target_: fvcore.common.param_scheduler.CosineParamScheduler
              start_value: 5e-4
              end_value: 1e-7
          lengths: [0.05, 0.95]
          interval_scaling: ['rescaled', 'rescaled']
      # - scheduler:
      #     _target_: fvcore.common.param_scheduler.CompositeParamScheduler
      #     schedulers:
      #       - _target_: fvcore.common.param_scheduler.LinearParamScheduler
      #         start_value: 1e-7
      #         end_value: 5e-5
      #       - _target_: fvcore.common.param_scheduler.CosineParamScheduler
      #         start_value: 5e-5
      #         end_value: 1e-7
      #     lengths: [0.05, 0.95]
      #     interval_scaling: ['rescaled', 'rescaled']
      #   param_names:
      #     - regressor.*
    weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.00001
      # - scheduler:
      #     _target_: fvcore.common.param_scheduler.ConstantParamScheduler
      #     value: 0.05
      #   param_names:
      #     - regressor.*

  gradient_clip:
    _target_: training.train_utils.gradient_clip.GradientClipper
    configs:
      - module_name: ["extractor", "concatconv", "gw", "ffn"]
        max_norm: 1.0  # feel free to reduce this if see instabilities
        norm_type: 2
      - module_name: ["head"]
        max_norm: 1.0  # feel free to reduce this if see instabilities
        norm_type: 2
      # - module_name: ["vit_refine"]
      #   max_norm: 1.0  # feel free to reduce this if see instabilities
      #   norm_type: 2
      - module_name: ["norm", "blocks"]
        max_norm: 1.0  # feel free to reduce this if see instabilities
        norm_type: 2
      # - module_name: ["regressor"]
      #   max_norm: 1.0  # feel free to reduce this if see instabilities
      #   norm_type: 2